INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 1', 'Employer 1', '2021-10-26', null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 2', 'Employer 2', '2021-10-01', '2021-10-26', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 3', 'Employer 3', '2021-09-01', '2021-10-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 4', 'Employer 4', '2021-08-01', '2021-09-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 5', 'Employer 5', '2021-07-01', '2021-08-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');

INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 6', 'Employer 6', '2021-06-01', '2021-07-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 7', 'Employer 7', '2021-05-01', '2021-06-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 8', 'Employer 8', '2021-04-01', '2021-05-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 9', 'Employer 9', '2021-03-01', '2021-04-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (position, employer, start_date, end_date, description) VALUES ('Job 10', 'Employer 10', '2021-01-01', '2021-03-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');

INSERT INTO joke (setup, joke) VALUES ('What did the evil chicken lay?', 'Deviled eggs.');
INSERT INTO joke (setup, joke) VALUES ('Why do you never see elephants hiding in trees?', 'Because they’re so good at it.');
INSERT INTO joke (setup, joke) VALUES ('Why do pirates not take a bath before they walk the plank?', 'They just wash up on shore.');
INSERT INTO joke (setup, joke) VALUES ('When does a joke become a “dad joke?”', 'When it becomes apparent.');
INSERT INTO joke (setup, joke) VALUES ('Why do cows wear bells?', 'Because their horns don''t work.');