INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (1, 'Job 1', 'Employer 1', '2021-10-26', null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (2, 'Job 2', 'Employer 2', '2021-10-01', '2021-10-26', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (3, 'Job 3', 'Employer 3', '2021-09-01', '2021-10-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (4, 'Job 4', 'Employer 4', '2021-08-01', '2021-09-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (5, 'Job 5', 'Employer 5', '2021-07-01', '2021-08-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');

INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (6, 'Job 6', 'Employer 6', '2021-06-01', '2021-07-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (7, 'Job 7', 'Employer 7', '2021-05-01', '2021-06-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (8, 'Job 8', 'Employer 8', '2021-04-01', '2021-05-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (9, 'Job 9', 'Employer 9', '2021-03-01', '2021-04-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');
INSERT INTO job (jobid, name, employer, start_date, end_date, description) VALUES (10, 'Job 10', 'Employer 10', '2021-01-01', '2021-03-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis tincidunt id aliquet risus.');